---
title: "try stuff"
format: html
editor: visual
---

```{r}
library(shiny)
library(here)
library(ggplot2)
library(tidyverse)
library(sf)
library(bslib)
library(maps)
library(mapdata)
library(kableExtra)
library(knitr)
library(ggfortify)
library(RColorBrewer)
library(markdown)
library(rnaturalearth)
```

# Inset Map

```{r}
 grade_colors <- c("A" = "green", "B" = "cyan", "C" = "orange", "D" = "firebrick1")

      base_plot <- ggplot() +
        geom_sf(data = enviroscreen_final, fill = "dodgerblue", color = "dodgerblue") +
        theme_void()

      # Add grade polygons
      grade_plot <- base_plot +
        geom_sf(data = enviroscreen_trimmed, aes(fill = 'canopy_pct')) +
        scale_fill_gradient(low = "lightskyblue", high = "navy", na.value = NA) +
        scale_color_manual(values = grade_colors) +
        labs(color = "Redlining Grade",fill = 'canopy_pct')+
        theme(legend.title = element_text(size = 16),  # Adjust legend title size
       legend.text = element_text(size = 16))

 grade_plot
```

```{r}
#check the crs of california 
# st_crs(california)
# st_crs(enviroscreen_final)

```

```{r}
#make an inset map of california 
usa <- map_data("usa")
california <- map_data("state") %>% 
  filter(region == "california")

#transform california data frame into a spatial object
california_sf <- california %>% 
  st_as_sf(coords = c("long", "lat"), crs = 4269) %>% 
  summarize(geometry = st_combine(geometry)) %>% # transform points into polygon
  st_cast("POLYGON")

```

```{r}
#inset map

california_inset <- ggplot() +
  geom_sf(data = california_sf, aes(), fill = "grey", color = "black") + 
  geom_sf(data = enviroscreen_final, aes(), fill = "dodgerblue", color = "dodgerblue") +
  theme_void() +
  theme(plot.background = element_rect(fill = "white", color = "black"))

california_inset

```

# Background map

```{r}
#update
base_plot <- ggplot() +
  geom_sf(data = enviroscreen_final, fill = "white", color = "black") +
  theme_void()
base_plot
```

Combine base plot and inset map
```{r}
library(cowplot)
ggdraw() + 
  draw_plot(base_plot, x = 0, y = 0, width = 1, height = 1) + 
  draw_plot(california_inset, x = 0, y = .05, width = .35, height = .35)

```


```{r}

#roads map of LA

library(osmdata)

# available_features()

la <- opq(bbox = 'Los Angeles, California') %>%
  add_osm_feature(key = 'highway', value = 'motorway') %>%
  osmdata_sf()

#plot the roads
la$osm_lines %>%
  ggplot() +
  geom_sf() +
  theme_void()

```
